#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
readonly PROJECT_ROOT
readonly ENV_FILE="${PROJECT_ROOT}/.env.docker"

START_STACK=true
SKIP_API_KEY=false

usage() {
    cat <<'EOF'
Usage: ./scripts/setup-macos-docker.sh [--no-start] [--skip-api-key]

Configure and start the fully containerized Refindery stack on macOS.
Docker must already be installed.

Options:
  --no-start      Write and validate .env.docker without starting the stack.
  --skip-api-key  Do not require a Voyage API key (indexing will not work yet).
  -h, --help      Show this help.

For unattended setup, provide VOYAGE_API_KEY in the environment.
EOF
}

fail() {
    printf 'error: %s\n' "$1" >&2
    exit 1
}

on_error() {
    printf 'error: Docker setup failed near line %s\n' "$1" >&2
}

trap 'on_error "${LINENO}"' ERR

has_env_value() {
    local key="$1"

    [[ -f "${ENV_FILE}" ]] || return 1
    awk -v key="${key}" '
        $0 ~ "^[[:space:]]*" key "[[:space:]]*=" {
            value = $0
            sub("^[[:space:]]*" key "[[:space:]]*=[[:space:]]*", "", value)
            if (value != "" && value != "\"\"" && value != "\047\047") {
                found = 1
            }
        }
        END { exit found ? 0 : 1 }
    ' "${ENV_FILE}"
}

set_env_value() {
    local key="$1"
    local value="$2"
    local temporary_file

    [[ "${value}" != *$'\n'* && "${value}" != *$'\r'* ]] || \
        fail "${key} must be a single-line value"

    temporary_file="$(mktemp "${ENV_FILE}.XXXXXX")"
    awk -v key="${key}" \
        '$0 !~ "^[[:space:]]*" key "[[:space:]]*=" { print }' \
        "${ENV_FILE}" > "${temporary_file}"
    printf '%s=%s\n' "${key}" "${value}" >> "${temporary_file}"
    chmod 600 "${temporary_file}"
    mv "${temporary_file}" "${ENV_FILE}"
}

ensure_env_value() {
    local key="$1"
    local value="$2"

    if ! has_env_value "${key}"; then
        set_env_value "${key}" "${value}"
    fi
}

ensure_docker_cli() {
    command -v docker >/dev/null 2>&1 || \
        fail "Docker is not installed or is not on PATH"
    docker compose version >/dev/null 2>&1 || \
        fail "Docker Compose is unavailable; install or update Docker Desktop"
}

ensure_docker_daemon() {
    local attempt

    if docker info >/dev/null 2>&1; then
        return
    fi

    command -v open >/dev/null 2>&1 || \
        fail "the Docker daemon is not running; start Docker Desktop"
    printf 'Starting Docker Desktop...\n'
    open -gja Docker
    for ((attempt = 1; attempt <= 60; attempt++)); do
        if docker info >/dev/null 2>&1; then
            return
        fi
        sleep 2
    done
    fail "Docker Desktop did not become ready within 120 seconds"
}

wait_for_refindery() {
    local deadline

    command -v curl >/dev/null 2>&1 || fail "curl is required to check readiness"
    printf 'Waiting for Refindery readiness...\n'
    deadline=$((SECONDS + 120))
    while ((SECONDS < deadline)); do
        if curl --fail --silent --show-error --max-time 2 \
            http://127.0.0.1:8000/readyz >/dev/null 2>&1; then
            return
        fi
        sleep 2
    done

    docker compose --env-file "${ENV_FILE}" ps >&2 || true
    docker compose --env-file "${ENV_FILE}" logs --tail 50 app >&2 || true
    fail "Refindery did not become ready within 120 seconds"
}

while (($# > 0)); do
    case "$1" in
        --no-start)
            START_STACK=false
            ;;
        --skip-api-key)
            SKIP_API_KEY=true
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        *)
            usage >&2
            fail "unknown option: $1"
            ;;
    esac
    shift
done

[[ "$(uname -s)" == "Darwin" ]] || fail "this setup script requires macOS"
ensure_docker_cli

voyage_api_key="${VOYAGE_API_KEY:-}"
if [[ -z "${voyage_api_key}" ]] && ! has_env_value "VOYAGE_API_KEY" && \
    [[ "${SKIP_API_KEY}" == false ]]; then
    if [[ -t 0 ]]; then
        read -r -s -p "Voyage API key: " voyage_api_key
        printf '\n'
        [[ -n "${voyage_api_key}" ]] || \
            fail "a Voyage API key is required (or use --skip-api-key)"
    else
        fail "set VOYAGE_API_KEY for unattended setup (or use --skip-api-key)"
    fi
fi

cd "${PROJECT_ROOT}"
umask 077
if [[ ! -f "${ENV_FILE}" ]]; then
    printf '# Generated by scripts/setup-macos-docker.sh\n' > "${ENV_FILE}"
fi
chmod 600 "${ENV_FILE}"

if [[ -n "${REFINDERY_AUTH_TOKEN:-}" ]]; then
    set_env_value "REFINDERY_AUTH_TOKEN" "${REFINDERY_AUTH_TOKEN}"
elif ! has_env_value "REFINDERY_AUTH_TOKEN"; then
    command -v openssl >/dev/null 2>&1 || \
        fail "openssl is required to generate an authentication token"
    set_env_value "REFINDERY_AUTH_TOKEN" "$(openssl rand -hex 24)"
fi

set_env_value "REFINDERY_VECTOR_STORE" "qdrant"
set_env_value "REFINDERY_QDRANT__URL" "http://qdrant:6333"
ensure_env_value "REFINDERY_QDRANT__COLLECTION" "refindery_chunks"
ensure_env_value "REFINDERY_EMBEDDER__PROVIDER" "voyage"
ensure_env_value "REFINDERY_EMBEDDER__MODEL" "voyage-3.5"
ensure_env_value "REFINDERY_EMBEDDER__DIM" "1024"
ensure_env_value "REFINDERY_EMBEDDER__MAX_INPUT_TOKENS" "32000"
ensure_env_value "REFINDERY_RERANKER__KIND" "api"
ensure_env_value "REFINDERY_RERANKER__PROVIDER" "voyage"
ensure_env_value "REFINDERY_RERANKER__MODEL" "rerank-2.5"
ensure_env_value "REFINDERY_ENTITY__EXTRACTOR_CHAIN" "'[\"spacy\"]'"

if [[ -n "${voyage_api_key}" ]]; then
    set_env_value "VOYAGE_API_KEY" "${voyage_api_key}"
fi

printf 'Validating the Docker configuration...\n'
docker compose --env-file "${ENV_FILE}" config --quiet

if [[ "${START_STACK}" == false ]]; then
    printf '\nDocker configuration is ready in %s.\n' "${ENV_FILE}"
    printf 'Start Refindery with:\n  docker compose --env-file %s up -d --build\n' \
        "${ENV_FILE}"
    exit 0
fi

ensure_docker_daemon
printf 'Building and starting Refindery with Qdrant...\n'
docker compose --env-file "${ENV_FILE}" up --detach --build
wait_for_refindery

printf '\nSetup complete. Refindery is ready at http://127.0.0.1:8000.\n'
printf 'Credentials and advanced settings are stored in %s.\n' "${ENV_FILE}"
printf 'Stop the stack with:\n  docker compose --env-file %s down\n' \
    "${ENV_FILE}"
