#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
readonly PROJECT_ROOT
readonly ENV_FILE="${PROJECT_ROOT}/.env"

START_SERVER=false
SKIP_API_KEY=false
BREW_BIN=""
UV_BIN=""

usage() {
    cat <<'EOF'
Usage: ./scripts/setup-macos.sh [--start] [--skip-api-key]

Install and configure Refindery on macOS without Docker.

Options:
  --start         Start Refindery after setup completes.
  --skip-api-key  Do not require a Voyage API key (indexing will not work yet).
  -h, --help      Show this help.

For unattended setup, provide VOYAGE_API_KEY in the environment.
EOF
}

fail() {
    printf 'error: %s\n' "$1" >&2
    exit 1
}

on_error() {
    printf 'error: setup failed near line %s\n' "$1" >&2
}

trap 'on_error "${LINENO}"' ERR

has_env_value() {
    local key="$1"

    [[ -f "${ENV_FILE}" ]] || return 1
    awk -v key="${key}" '
        $0 ~ "^[[:space:]]*" key "[[:space:]]*=" {
            value = $0
            sub("^[[:space:]]*" key "[[:space:]]*=[[:space:]]*", "", value)
            if (value != "" && value != "\"\"" && value != "\047\047") {
                found = 1
            }
        }
        END { exit found ? 0 : 1 }
    ' "${ENV_FILE}"
}

set_env_value() {
    local key="$1"
    local value="$2"
    local temporary_file

    [[ "${value}" != *$'\n'* && "${value}" != *$'\r'* ]] || \
        fail "${key} must be a single-line value"
    [[ "${value}" != *[[:space:]]* ]] || \
        fail "${key} must not contain whitespace"

    temporary_file="$(mktemp "${ENV_FILE}.XXXXXX")"
    awk -v key="${key}" \
        '$0 !~ "^[[:space:]]*" key "[[:space:]]*=" { print }' \
        "${ENV_FILE}" > "${temporary_file}"
    printf '%s=%s\n' "${key}" "${value}" >> "${temporary_file}"
    chmod 600 "${temporary_file}"
    mv "${temporary_file}" "${ENV_FILE}"
}

ensure_env_value() {
    local key="$1"
    local value="$2"

    if ! has_env_value "${key}"; then
        set_env_value "${key}" "${value}"
    fi
}

install_homebrew() {
    local candidate

    if command -v brew >/dev/null 2>&1; then
        BREW_BIN="$(command -v brew)"
        return
    fi

    command -v curl >/dev/null 2>&1 || fail "curl is required to install Homebrew"
    printf 'Homebrew is not installed; installing it now...\n'
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    for candidate in /opt/homebrew/bin/brew /usr/local/bin/brew; do
        if [[ -x "${candidate}" ]]; then
            BREW_BIN="${candidate}"
            eval "$("${BREW_BIN}" shellenv)"
            return
        fi
    done
    fail "Homebrew installed but its brew executable was not found"
}

while (($# > 0)); do
    case "$1" in
        --start)
            START_SERVER=true
            ;;
        --skip-api-key)
            SKIP_API_KEY=true
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        *)
            usage >&2
            fail "unknown option: $1"
            ;;
    esac
    shift
done

[[ "$(uname -s)" == "Darwin" ]] || fail "this setup script requires macOS"

voyage_api_key="${VOYAGE_API_KEY:-}"
if [[ -z "${voyage_api_key}" ]] && ! has_env_value "VOYAGE_API_KEY" && \
    [[ "${SKIP_API_KEY}" == false ]]; then
    if [[ -t 0 ]]; then
        read -r -s -p "Voyage API key: " voyage_api_key
        printf '\n'
        [[ -n "${voyage_api_key}" ]] || \
            fail "a Voyage API key is required (or use --skip-api-key)"
    else
        fail "set VOYAGE_API_KEY for unattended setup (or use --skip-api-key)"
    fi
fi

install_homebrew

printf 'Installing Python 3.13 and uv with Homebrew...\n'
"${BREW_BIN}" install python@3.13 uv

PYTHON_BIN="$("${BREW_BIN}" --prefix python@3.13)/bin/python3.13"
readonly PYTHON_BIN
UV_BIN="$("${BREW_BIN}" --prefix uv)/bin/uv"
[[ -x "${PYTHON_BIN}" ]] || fail "Homebrew Python 3.13 was not found"
[[ -x "${UV_BIN}" ]] || fail "Homebrew uv was not found"

cd "${PROJECT_ROOT}"
printf 'Syncing the locked Refindery environment with NER support...\n'
"${UV_BIN}" sync --python "${PYTHON_BIN}" --locked --extra ner

umask 077
if [[ ! -f "${ENV_FILE}" ]]; then
    printf '# Generated by scripts/setup-macos.sh\n' > "${ENV_FILE}"
fi
chmod 600 "${ENV_FILE}"

if [[ -n "${REFINDERY_AUTH_TOKEN:-}" ]]; then
    set_env_value "REFINDERY_AUTH_TOKEN" "${REFINDERY_AUTH_TOKEN}"
else
    ensure_env_value \
        "REFINDERY_AUTH_TOKEN" \
        "$("${PYTHON_BIN}" -c 'import secrets; print(secrets.token_hex(24))')"
fi

set_env_value "REFINDERY_VECTOR_STORE" "lancedb"
ensure_env_value "REFINDERY_RERANKER__PROVIDER" "voyage"
ensure_env_value "REFINDERY_RERANKER__MODEL" "rerank-2.5"

if [[ -n "${voyage_api_key}" ]]; then
    set_env_value "VOYAGE_API_KEY" "${voyage_api_key}"
fi

mkdir -p data

printf 'Validating the generated local configuration...\n'
"${UV_BIN}" run --env-file "${ENV_FILE}" python - <<'PY'
from refindery.config import VectorStoreKind, load_settings

settings = load_settings()
if settings.vector_store is not VectorStoreKind.LANCEDB:
    raise SystemExit("macOS setup must configure LanceDB")
PY

if [[ "${SKIP_API_KEY}" == false ]]; then
    "${UV_BIN}" run --env-file "${ENV_FILE}" python - <<'PY'
import os

if not os.environ.get("VOYAGE_API_KEY"):
    raise SystemExit("VOYAGE_API_KEY was not loaded")
PY
fi

printf '\nSetup complete. Local state will be stored in %s/data.\n' "${PROJECT_ROOT}"

if [[ "${START_SERVER}" == true ]]; then
    printf 'Starting Refindery at http://127.0.0.1:8000 ...\n'
    exec "${UV_BIN}" run --env-file "${ENV_FILE}" refindery serve
fi

printf 'Start Refindery with:\n  %s run --env-file %s refindery serve\n' \
    "${UV_BIN}" "${ENV_FILE}"
